# Generated by Django 4.2.4 on 2023-09-14 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
