# Generated by Django 4.2.4 on 2023-09-30 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_options_variation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'variation', 'verbose_name_plural': 'variations'},
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='images',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='variation',
            name='actual_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='variation',
            name='images',
            field=models.ImageField(default=None, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='variation',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='variation',
            name='stock',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
