# Generated by Django 4.2.4 on 2023-10-06 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variation_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variation',
            old_name='images',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='variation',
            name='image2',
            field=models.ImageField(default=None, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='variation',
            name='image3',
            field=models.ImageField(default=None, upload_to='photos/products/'),
        ),
        migrations.AddField(
            model_name='variation',
            name='image4',
            field=models.ImageField(default=None, upload_to='photos/products/'),
        ),
    ]
