# Generated by Django 4.2.4 on 2023-11-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_variation_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('discount', models.IntegerField(default=100)),
                ('valid_from', models.DateField()),
                ('valid_to', models.DateField()),
                ('is_expired', models.BooleanField(default=False)),
            ],
        ),
    ]
