# Generated by Django 4.2.4 on 2023-11-11 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_coupon_minimum_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='coupon_name',
            field=models.CharField(default='discount coupon', max_length=20),
        ),
    ]
