# Generated by Django 4.2.4 on 2023-11-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_coupon_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
