# Generated by Django 4.2.4 on 2023-09-12 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
    ]
