# Generated by Django 4.2.4 on 2023-09-13 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_is_activate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sub_category',
            name='Sub_Category_image',
            field=models.ImageField(default=None, upload_to='subcategories/'),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sub_category',
            name='sub_category_description',
            field=models.TextField(default=None, max_length=225),
        ),
        migrations.AlterField(
            model_name='sub_category',
            name='sub_category_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
