# Generated by Django 4.2.4 on 2023-09-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_rename_sub_category_image_sub_category_sub_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_Category_image',
            field=models.ImageField(default=None, upload_to='photos/subcategories/'),
        ),
    ]
