# Generated by Django 4.2.4 on 2023-09-15 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0005_alter_sub_category_sub_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=models.ImageField(default=None, upload_to='photos/cateogries/'),
        ),
    ]
