# Generated by Django 4.2.4 on 2023-09-15 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0007_alter_category_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub_category',
            name='sub_Category_image',
            field=models.ImageField(default=None, upload_to='photos/sub_categories/'),
        ),
    ]
