# Generated by Django 4.2.4 on 2023-09-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0008_alter_sub_category_sub_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=models.ImageField(upload_to='photos/categories/'),
        ),
    ]
